-- PLAYERS TABLE
CREATE TABLE PLAYERS_DG_TMP (
    "INDEX"  INTEGER,
    NICKNAME TEXT,
    TAGLINE  TEXT,
    ROLE     TEXT,
    CONSTRAINT PLAYERS_PK PRIMARY KEY (NICKNAME)
);

INSERT INTO PLAYERS_DG_TMP ("INDEX", NICKNAME, TAGLINE, ROLE)
SELECT "INDEX", NICKNAME, TAGLINE, ROLE
FROM PLAYERS;

DROP TABLE PLAYERS;

ALTER TABLE PLAYERS_DG_TMP
    RENAME TO PLAYERS;

CREATE INDEX IX_PLAYERS_INDEX
    ON PLAYERS ("INDEX");

-- CHAMPION_POOL TABLE
CREATE TABLE CHAMPION_POOL_DG_TMP (
    "INDEX"  INTEGER,
    ROLE     TEXT,
    CHAMPION TEXT,
    CONSTRAINT CHAMPION_POOL_PK PRIMARY KEY ("INDEX")
);

INSERT INTO CHAMPION_POOL_DG_TMP ("INDEX", ROLE, CHAMPION)
SELECT "INDEX", ROLE, CHAMPION
FROM CHAMPION_POOL;

DROP TABLE CHAMPION_POOL;

ALTER TABLE CHAMPION_POOL_DG_TMP
    RENAME TO CHAMPION_POOL;

CREATE INDEX IX_CHAMPION_POOL_INDEX
    ON CHAMPION_POOL ("INDEX");

-- CHAMPIONS TABLE
CREATE TABLE CHAMPIONS_DG_TMP (
    "INDEX"              INTEGER,
    ID                   TEXT,
    NAME                 TEXT,
    TITLE                TEXT,
    ATTACK               INTEGER,
    DEFENSE              INTEGER,
    MAGIC                INTEGER,
    DIFFICULTY           INTEGER,
    TAGS                 TEXT,
    PARTYPE              TEXT,
    HP                   INTEGER,
    HPPERLEVEL           INTEGER,
    MP                   INTEGER,
    MPPERLEVEL           REAL,
    MOVESPEED            INTEGER,
    ARMOR                INTEGER,
    ARMORPERLEVEL        REAL,
    SPELLBLOCK           INTEGER,
    SPELLBLOCKPERLEVEL   REAL,
    ATTACKRANGE          INTEGER,
    HPREGEN              REAL,
    HPREGENPERLEVEL      REAL,
    MPREGEN              REAL,
    MPREGENPERLEVEL      REAL,
    CRIT                 INTEGER,
    CRITPERLEVEL         INTEGER,
    ATTACKDAMAGE         INTEGER,
    ATTACKDAMAGEPERLEVEL REAL,
    ATTACKSPEEDPERLEVEL  REAL,
    ATTACKSPEED          REAL,
    CONSTRAINT CHAMPIONS_PK PRIMARY KEY (ID)
);

INSERT INTO CHAMPIONS_DG_TMP ("INDEX", ID, NAME, TITLE, ATTACK, DEFENSE, MAGIC, DIFFICULTY, TAGS, PARTYPE, HP,
                             HPPERLEVEL, MP, MPPERLEVEL, MOVESPEED, ARMOR, ARMORPERLEVEL, SPELLBLOCK,
                             SPELLBLOCKPERLEVEL, ATTACKRANGE, HPREGEN, HPREGENPERLEVEL, MPREGEN, MPREGENPERLEVEL, CRIT,
                             CRITPERLEVEL, ATTACKDAMAGE, ATTACKDAMAGEPERLEVEL, ATTACKSPEEDPERLEVEL, ATTACKSPEED)
SELECT "INDEX",
       ID,
       NAME,
       TITLE,
       ATTACK,
       DEFENSE,
       MAGIC,
       DIFFICULTY,
       TAGS,
       PARTYPE,
       HP,
       HPPERLEVEL,
       MP,
       MPPERLEVEL,
       MOVESPEED,
       ARMOR,
       ARMORPERLEVEL,
       SPELLBLOCK,
       SPELLBLOCKPERLEVEL,
       ATTACKRANGE,
       HPREGEN,
       HPREGENPERLEVEL,
       MPREGEN,
       MPREGENPERLEVEL,
       CRIT,
       CRITPERLEVEL,
       ATTACKDAMAGE,
       ATTACKDAMAGEPERLEVEL,
       ATTACKSPEEDPERLEVEL,
       ATTACKSPEED
FROM CHAMPIONS;

DROP TABLE CHAMPIONS;

ALTER TABLE CHAMPIONS_DG_TMP
    RENAME TO CHAMPIONS;

CREATE INDEX IX_CHAMPIONS_INDEX
    ON CHAMPIONS ("INDEX");
